apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: aws-secrets-manager
spec:
  provider:
    aws:
      service: SecretsManager
      region: eu-west-2
      auth:
        jwt:
          # Assumes IRSA is configured for the default external-secrets service account
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets
